# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 24.9.1
_libgcc_mutex=0.1=main
_openmp_mutex=5.1=1_gnu
accelerate=1.10.1=pypi_0
annotated-types=0.7.0=pypi_0
blis=0.7.11=pypi_0
bzip2=1.0.8=h5eee18b_6
ca-certificates=2025.11.4=h06a4308_0
catalogue=2.0.10=pypi_0
certifi=2025.11.12=pypi_0
charset-normalizer=3.4.4=pypi_0
click=8.1.8=pypi_0
cmake=4.2.0=pypi_0
confection=0.1.5=pypi_0
cymem=2.0.13=pypi_0
en-core-web-sm=3.6.0=pypi_0
expat=2.7.3=h3385a95_0
filelock=3.19.1=pypi_0
fsspec=2025.10.0=pypi_0
hf-xet=1.2.0=pypi_0
huggingface-hub=0.36.0=pypi_0
idna=3.11=pypi_0
jinja2=3.1.6=pypi_0
joblib=1.5.2=pypi_0
langcodes=3.5.0=pypi_0
language-data=1.3.0=pypi_0
ld_impl_linux-64=2.44=h153f514_2
libffi=3.4.4=h6a678d5_1
libgcc=15.2.0=h69a1729_7
libgcc-ng=15.2.0=h166f726_7
libgomp=15.2.0=h4751f2c_7
libnsl=2.0.0=h5eee18b_0
libstdcxx=15.2.0=h39759b7_7
libstdcxx-ng=15.2.0=hc03a8fd_7
libuuid=1.41.5=h5eee18b_0
libxcb=1.17.0=h9b100fa_0
libzlib=1.3.1=hb25bd0a_0
lit=18.1.8=pypi_0
marisa-trie=1.3.1=pypi_0
markupsafe=3.0.3=pypi_0
mpmath=1.3.0=pypi_0
murmurhash=1.0.15=pypi_0
ncurses=6.5=h7934f7d_0
networkx=3.2.1=pypi_0
numpy=1.25.2=pypi_0
nvidia-cublas-cu11=11.10.3.66=pypi_0
nvidia-cuda-cupti-cu11=11.7.101=pypi_0
nvidia-cuda-nvrtc-cu11=11.7.99=pypi_0
nvidia-cuda-runtime-cu11=11.7.99=pypi_0
nvidia-cudnn-cu11=8.5.0.96=pypi_0
nvidia-cufft-cu11=10.9.0.58=pypi_0
nvidia-curand-cu11=10.2.10.91=pypi_0
nvidia-cusolver-cu11=11.4.0.1=pypi_0
nvidia-cusparse-cu11=11.7.4.91=pypi_0
nvidia-nccl-cu11=2.14.3=pypi_0
nvidia-nvtx-cu11=11.7.91=pypi_0
openssl=3.0.18=hd6dcaed_0
packaging=25.0=pypi_0
pandas=2.0.3=pypi_0
pathlib-abc=0.1.1=pypi_0
pathy=0.11.0=pypi_0
pip=25.3=pyhc872135_0
preshed=3.0.12=pypi_0
psutil=7.1.3=pypi_0
pthread-stubs=0.3=h0ce48e5_1
pydantic=2.12.4=pypi_0
pydantic-core=2.41.5=pypi_0
python=3.9.25=h0dcde21_1
python-dateutil=2.9.0.post0=pypi_0
pytz=2025.2=pypi_0
pyyaml=6.0.3=pypi_0
readline=8.3=hc2a1206_0
regex=2025.11.3=pypi_0
requests=2.32.5=pypi_0
safetensors=0.7.0=pypi_0
scikit-learn=1.3.0=pypi_0
scipy=1.13.1=pypi_0
sentencepiece=0.2.1=pypi_0
setuptools=80.9.0=py39h06a4308_0
six=1.17.0=pypi_0
smart-open=6.4.0=pypi_0
spacy=3.6.1=pypi_0
spacy-legacy=3.0.12=pypi_0
spacy-loggers=1.0.5=pypi_0
sqlite=3.51.0=h2a70700_0
srsly=2.5.2=pypi_0
sympy=1.14.0=pypi_0
thinc=8.1.12=pypi_0
threadpoolctl=3.6.0=pypi_0
tk=8.6.15=h54e0aa7_0
tokenizers=0.13.3=pypi_0
torch=2.0.1=pypi_0
tqdm=4.66.1=pypi_0
transformers=4.31.0=pypi_0
triton=2.0.0=pypi_0
typer=0.9.4=pypi_0
typing-extensions=4.15.0=pypi_0
typing-inspection=0.4.2=pypi_0
tzdata=2025.2=pypi_0
urllib3=2.5.0=pypi_0
wasabi=1.1.3=pypi_0
wheel=0.45.1=py39h06a4308_0
xorg-libx11=1.8.12=h9b100fa_1
xorg-libxau=1.0.12=h9b100fa_0
xorg-libxdmcp=1.1.5=h9b100fa_0
xorg-xorgproto=2024.1=h5eee18b_1
xz=5.6.4=h5eee18b_1
zlib=1.3.1=hb25bd0a_0
